# Generated by Django 5.0.1 on 2024-01-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
